name: Waka Readme
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_SECRET }}
          STOP_AT_OTHER: false
          SHOW_MORE: true
          IGNORED_LANGUAGES: YAML JSON TOML NETRW CONF Blade "Blade Template" HTML CSS
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_TIME: true
          TIME_RANGE: all_time
          SHOW_MASKED_TIME: false
